services:
  - type: web
    name: face-api
    env: python
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    pythonVersion: 3.10.11
